### ISSUE TITLE
copies all ${SDCCDIR}/bin to SDCC

### ISSUE THREAD

**Issue by konsumer** [Zal0/gbdk-2020#10]
When I do an install a bunch of unnecessary files are copied (all of `/usr/bin`.)

I am working on [this](https://github.com/konsumer/docker-gb-dev) complete docker dev environment for gameboy. It currently uses [gbdk-n](https://github.com/andreasjhkarlsson/gbdk-n) but that lib has some issues that make it not really workable, so I'd like to switch to this one. When I run this:

```
export SDCCDIR=/usr
git clone https://github.com/Zal0/gbdk-2020.git /opt/gbdk \
  && cd /opt/gbdk \
  && make && make install
```

I notice it copies all of `${SDCCDIR}/bin`, which in this case is a lot of things. I'd like to use the OS-installed copy of sdcc, if possible.

I'd recommend copying (or better: sym-linking) just the sdcc bin files, which is this:

```
as2gbmap
makebin
packihx
sdar
sdas390
sdas6808
sdas8051
sdasgb
sdasrab
sdasstm8
sdastlcs90
sdasz80
sdcc
sdcclib
sdcpp
sdld
sdldstm8
sdnm
sdobjcopy
sdranlib
sdld6808
sdldgb
sdldz80
```

Maybe even not copy or symlink, and just rely on path, if `sdcc` is in it.

For information, this is the version that comes with docker's current `debian:latest` container, if you install `sdcc` package:

```
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ds390/TININative/ds400/hc08/s08/stm8 3.8.0 #10562 (Linux)
```

**Comment by Zal0** [comment]
Hi Konsumer. Thanks for the suggestions

GBDK installation should be independent of what the user has on his computer. So even if he already has SDCC I prefer not to trust its installation or create any kind of dependency here (I've seen lots of problems in the past with people having different versions of the compiler installed). That's why I don't think relying on path or symlinking is a good idea. GBDK will always use the version that comes with the release. (For advanced users it shouldn't be a problem to symlink and use an installed version anyway)

It also seems that the required files on windows and unix are different and just removing a few files complicates things (There are only 5 extra files not listed there saving just 391kb, something that I think is not a problem nowadays)
