### ISSUE TITLE
License of some files is plain LGPL with no SDCC exception

### ISSUE THREAD

**Issue by AntonioND** [Zal0/gbdk-2020#114]
In most files that have LGPL license, there is an exception to use them with SDCC:

https://github.com/Zal0/gbdk-2020/blob/d7265ebb0e80e2bd2c365161a864bede3ac2292c/gbdk-lib/libc/asm/gbz80/mul.s

But there are a few files that don't have the exception:

https://github.com/Zal0/gbdk-2020/blob/d7265ebb0e80e2bd2c365161a864bede3ac2292c/gbdk-lib/libc/_modulong.c
https://github.com/Zal0/gbdk-2020/blob/d7265ebb0e80e2bd2c365161a864bede3ac2292c/gbdk-lib/libc/_modslong.c
https://github.com/Zal0/gbdk-2020/blob/d7265ebb0e80e2bd2c365161a864bede3ac2292c/gbdk-lib/libc/_divslong.c

This means that some closed-source games that are using the division functions introduced by the compiler are not complying with the library. It's unlikely that many games are affected, though, as it affects 32 bit division, which is probably uncommon.

**Comment by untoxa** [comment]
The most content of  files is garbage from the point of gbdk. Gameboy uses a generic C implementation at the end of those files, that contain zero know-how and copied somewhere from public domain. So you may just cleanup them. Also those files are taken from SDCC native library, so that “problem” is simply a mistake in sdcc library.

**Comment by bbbbbr** [comment]
It looks like those files were primarily written by Sandeep Dutta who is the original author of SDCC. So it's likely the SDCC project intends for the same exemption to apply, especially given the statements below. The SDCC would have the definitive answer for this.

https://sourceforge.net/p/sdcc/discussion/1864/thread/c8cd2cb2/#8ba6
>  Borut Ražem - 2009-12-30
>
> The initiative to change the sdcc library license in the way that it can be used in "closed source" projects has been started long time ago. I asked the authors if they agree with the license change and which  license they prefer, but only few answered. You can see results on sddc wiki pages:
> http://sourceforge.net/apps/trac/sdcc/wiki/SDCC%20Library%20Licenses and http://sdcc.sourceforge.net/wiki/index.php?page=Library+License+Selection.
> 
> I think that you can consider all files, which authors agreed to release them under GPL+LE license, as it they are already released under GPL+LE.
> 
> It would be really nice if we could solve this for the next sdcc release….
> 
> Borut 


https://sourceforge.net/p/sdcc/wiki/SDCC%20Library%20Licenses/
> The great majority of SDCC run-time libraries are licensed under the GPLv2+LE which allows linking of sdcc run time libraries with both free and non-free (proprietary, closed source) applications.
> 
> The exception are PIC device libraries and header files which are derived from Microchip header (.inc) and linker script (.lkr) files. Microchip claims copyright on those, which might or might not be a valid claim. Microchip requires that "The header files should state that they are only to be used with authentic Microchip devices" which makes them incompatible with the GPL.

**Comment by bbbbbr** [comment]
Turns out those files DO have the exemption, GBDK-2020 just has ancient versions from before they added the license exemption. 

https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/_modulong.c
https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/_modslong.c
https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/_divslong.c

The license change was made in 2010. 
https://sourceforge.net/p/sdcc/code/5737/
> * device/lib/*.c: sdcc library license changed to GPL+LE

So we can just pull in the updated files (or possibly just add the exemption into the old versions?) and this should be done.

**Comment by AntonioND** [comment]
You can't just change the license of a file in general, you should just get the updated version.

**Comment by bbbbbr** [comment]
> You can't just change the license of a file in general, you should just get the updated version.
> 
> EDIT: Well, if the code is the same, then the result is the same, that's what I meant by "in general you can't".

In general, true. In this case the context should be considered. To be explicit:
* The SDCC project obtained permission from the original file authors and contributors who made changed to re-license them. They did not remove code or make other changes in order to complete that transition (at least for the files in question), so we can expect the re-licensing applies to the original and subsequent versions leading up to the re-licensing.
* 99% of the changes since the versions here are either trivial or cosmetic- comments added, whitespace changes, a couple new #ifdefs sprinkled in and some variables mass-renamed in divslong  ("a/b[0/1/2/3]" renamed to "x/y[0/1/2/3]). One could go through the motion of adding the new files then deleting the unused ifdefs and renaming the variables back to reach the same effective result in two steps instead of one. Here is the diff for modulong: https://www.diffchecker.com/4uX1jV9R .
