### ISSUE TITLE
bank overflow checking in LCC

### ISSUE THREAD

**Issue by untoxa** [Zal0/gbdk-2020#72]
that should be done in SDCC's makebin tool, but we might wait for a decade for that, so, it is nice to implement that ourselves instead, that is easy: https://gbdev.gg8.se/forums/viewtopic.php?pid=4540#p4540

**Comment by bbbbbr** [comment]
A first pass at a small tool for checking IHX overlaps. It builds for Linux and Windows (mingw).
https://github.com/bbbbbr/ihx_check

- It does some merging of adjacent data blocks to reduce the number of comparisons, since in the ihx file they typically 32 bytes at the largest. That can be changed if we want to test all of them individually.

- By default it just prints warnings without changing an error code, but it can be instructed to treat the warnings as errors with the `-e` switch after the .ihx filename.

Some example output with a couple banks overflowing into others by various amounts.
```$ ihx_check.exe banks.ihx
Warning: Multiple write of 16384 bytes at 0x8000 -> 0xbfff. Bank overflow?  (8000 - bfff and 8000 - bfff)
Warning: Multiple write of     1 bytes at 0xc000 -> 0xc000. Bank overflow?  (c000 - c01e and c000 - c000)
Warning: Multiple write of    28 bytes at 0xc000 -> 0xc01b. Bank overflow?  (c000 - c01e and c000 - c01b)
Warning: Multiple write of     1 bytes at 0xc000 -> 0xc000. Bank overflow?  (c000 - c000 and c000 - c01b)
```

**Comment by untoxa** [comment]
"Bank overflow?" -- you age guessing? :)
```
.area area1
.org 0x500
.db 0, 1, 2

.area area2
.org 0x501
.db 3
```
nothing overflows here. just output addresses and values like the old tool did.

**Comment by bbbbbr** [comment]
@Zal0 Any preferences on this tool?

The "Bank overflow?" text was meant as a hint to the user about what might be going wrong (a question that occurs) and the title of this ticket does happen to be "bank overflow checking". :) No problem though, I can remove the hinting.

I could also change to printing "addresses and values", but a couple points in favor of summarizing the overlap instead:
* Since the address overlap can run into the 100-1000s of bytes, summarizing provides a more compact warning that doesn't scroll for multiple pages.
* Reporting the overlap size in bytes also makes it easier to figure out how much size needs to be reduced in cases of overflow (such as https://gbdev.gg8.se/forums/viewtopic.php?pid=4540)
* In order to report the actual changed values, the tool would need to mostly construct the ROM. It's do-able but seems like scope creep.

Also, for historical reference, here is a list of warnings that were produced by the old gbz80 linker. Some of which have equivalents in `makebin`.
```
fprintf(stderr, "ERROR: address overflow (addr %lx >= %lx)\n", pos, ROMSIZE);
fprintf(stderr, "ERROR: bank overflow (addr %x > %x)\n", current_rom_bank, nb_rom_banks);
fprintf(stderr, "ERROR: address underflow (addr %lx < %lx)\n", pos, BANKSTART);
fprintf(stderr, "ERROR: only 1 32kB segment with 2 bank\n");
fprintf(stderr, "WARNING: possibly wrote twice at addr %lx (%02X->%02X)\n", pos, rtval[i], cart[pos/SEGSIZE][pos%SEGSIZE]);
fprintf(stderr, "ERROR: cartridge size overflow (addr %lx >= %lx)\n", pos, CARTSIZE);
fprintf(stderr, "WARNING: unsupported number of ROM banks (%d)\n", nb_rom_banks);
fprintf(stderr, "WARNING: unsupported number of RAM banks (%d)\n", nb_ram_banks);

```

**Comment by untoxa** [comment]
WARINIG: Overwrite at 0x0200 with [0x01,0x11,0x08,0x04]

up to 16 bytes in a row

i don't think old values matter much for the user (new values too, you can't say what is it without maps in most of the cases). we also need a switch that treats warning as an error. because you not always see the warnings: might be useful for gb studio.

**Comment by bbbbbr** [comment]
The switch is already in there:

> By default it just prints warnings without changing an error code, but it can be instructed to treat the warnings as errors with the -e switch after the .ihx filename
